### ISSUE TITLE
Website: host it for me, host it myself buttons not working

### ISSUE THREAD

**Issue by awitherow** [codelitdev/courselit#23]

**Comment by rajat1saxena** [comment]
I am in the process of building the website. I will update it soon.

**Comment by awitherow** [comment]
Nice @rajat1saxena I sent you an email, I would like to help you with this project... Could you get back to me?

**Comment by rajat1saxena** [comment]
@awitherow Thank you. I will get back to you soon enough.

**Comment by rajat1saxena** [comment]
Please check the updated `Get started` section. https://courselit.codelit.dev/#getstarted
