### ISSUE TITLE
CourseLit branding in automated emails

### ISSUE THREAD

**Issue by rajat1saxena** [codelitdev/courselit#395]
The automated emails should have `Powered by CourseLit` branding at the bottom of the emails sent by the system.

The emails to have this footer include:

- The OTP email
- The sales notification email to the admin
- The `Welcome email` to the enroller
- Other system emails

## Settings

If the `Remove CourseLit branding` is unchecked in the the settings, then do not include this footer.

**Comment by varshasx** [comment]
Closing this in favour of #384
